apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: euphoria-season-3
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/euphoria-season-3
    newTag: bf927656603c799f4fd636b4d2406388133d7987
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: euphoria-season-3
      app.kubernetes.io/part-of: euphoria-season-3
