apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: euphoria-season-3
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/euphoria-season-3
    newTag: ec6998a118e6798a1389db4e42c1056e867a7bb8
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: euphoria-season-3
      app.kubernetes.io/part-of: euphoria-season-3
